from pathlib import Path


STATIC = Path("app/static")


def source(name: str) -> str:
    return (STATIC / name).read_text(encoding="utf-8")


def plan_source() -> str:
    javascript = source("app.js")
    return javascript[
        javascript.index("function planKindLabel"):
        javascript.index("function transactionTitle")
    ]


def test_mobile_plan_and_analytics_use_frozen_copy_and_headers():
    html = source("index.html")

    assert 'id="add-plan-rule"' in html
    assert 'class="mobile-plan-add-icon"' in html
    assert "Plan what comes next" in html
    assert (
        "Expected income, required expenses, subscriptions. "
        "Plan never changes real balances."
    ) in html
    analytics = html[
        html.index('id="view-analytics"'):
        html.index('</section>', html.index('id="view-analytics"')) + len('</section>')
    ]
    assert 'id="analytics-profile-trigger"' in analytics
    assert "⚡" in analytics
    assert "Coming soon" in analytics
    assert "Income, spending, and trends arrive once the core ledger is stable." in analytics
    for forbidden in ("canvas", "chart", "range", "filter"):
        assert forbidden not in analytics.lower()


def test_mobile_plan_is_rule_centric_and_bounds_each_card():
    javascript = plan_source()

    assert "function mobilePlanRuleCardNode" in javascript
    assert "if (isMobileViewport()) return mobilePlanRuleCardNode(rule)" in javascript
    assert "nearestRuleOccurrences(rule)" in javascript
    assert "overdue[0] ?? null" in javascript
    assert "future[0] ?? null" in javascript
    assert "mobilePlanOccurrenceNode(nearestOverdue, { overdueCount })" in javascript
    assert "mobilePlanOccurrenceNode(nearestFuture)" in javascript
    assert "`${overdueCount} overdue`" in javascript
    assert 'show.textContent = "Show"' in javascript
    assert "openMobilePlanRuleHistory(rule, show)" in javascript
    assert "plan-occurrence-groups" not in javascript


def test_mobile_rule_form_uses_adapter_decimal_and_dynamic_account_label():
    javascript = plan_source()
    form = javascript[
        javascript.index("function buildMobilePlanRuleFormBody"):
        javascript.index("async function openPlanRule")
    ]

    for mobile_kind in (
        "expectedIncome", "requiredExpense", "subscription",
        "reserveTransfer", "otherExpense",
    ):
        assert mobile_kind in form
    assert 'kind: draft.mobileKind' in form
    assert 'amount: draft.amount.trim()' in form
    assert 'account_id: draft.accountId' in form
    assert 'draft.mobileKind === "expectedIncome" ? "To account" : "From account"' in form
    assert 'label: "Category"' in form
    assert 'label: "Asset"' in form
    assert 'label: "Repeats"' in form
    assert 'label: "First due"' in form
    assert "parseFloat" not in form
    assert "Number(draft.amount" not in form


def test_mobile_plan_item_actions_are_one_row_in_exact_order():
    javascript = plan_source()
    item = javascript[
        javascript.index("function buildMobilePlanItemBody"):
        javascript.index("function openMobilePlanItem")
    ]

    edit = item.index('addAction("Edit rule"')
    skip = item.index('addAction("Skip"')
    link = item.index('addAction("Link transaction"')
    assert edit < skip < link
    assert 'actionRow.className = "mobile-plan-item-actions"' in item
    assert "openMobilePlanRuleForm(rule" in item
    assert "skipMobilePlanOccurrence(occurrence" in item
    assert "openMobilePlanLink(null" in item


def test_mobile_skip_and_delete_use_only_accepted_plan_commands():
    javascript = plan_source()

    skip = javascript[
        javascript.index("async function skipMobilePlanOccurrence"):
        javascript.index("function buildMobilePlanItemBody")
    ]
    assert '`/api/v1/workspaces/${state.context.workspace.id}/plan-occurrences/${occurrence.id}/skip`' in skip
    assert "archive" not in skip
    remove = javascript[
        javascript.index("function openMobileDeletePlanRule"):
        javascript.index("async function skipMobilePlanOccurrence")
    ]
    assert 'title: "Delete this rule?"' in remove
    assert (
        "Upcoming items generated by it disappear from Plan. "
        "Already linked transactions stay untouched."
    ) in remove
    assert '`/api/v1/workspaces/${state.context.workspace.id}/plan-rules/${rule.id}/archive`' in remove
    for forbidden in ("/pay", "/receive", "window.confirm"):
        assert forbidden not in remove + skip


def test_mobile_link_filters_semantic_type_not_account_or_asset():
    javascript = source("app.js")
    matching = javascript[
        javascript.index("function transactionMatchesOccurrence"):
        javascript.index("async function openPlanLink")
    ]
    mobile_link = javascript[
        javascript.index("async function openMobilePlanLink"):
        javascript.index("function transactionEditAccountChoices")
    ]

    assert 'transaction.type === expected' in matching
    assert 'transaction.status === "posted"' in matching
    assert "account_id" not in matching
    assert "asset.code" not in matching
    assert 'status=posted&limit=100' in mobile_link
    assert "transactionMatchesOccurrence(item, occurrence)" in mobile_link
    assert "occurrenceId: occurrence?.id || null" in mobile_link
    assert "transactionId: transaction?.id || null" in mobile_link
    assert "occurrences[0]" not in mobile_link
    assert "transactions[0]" not in mobile_link
    assert "primaryDisabled: () => !draft.occurrenceId || !draft.transactionId" in mobile_link
    assert '`/api/v1/workspaces/${state.context.workspace.id}/plan-occurrences/${draft.occurrenceId}/link-transaction`' in mobile_link
    assert 'transaction_id: Number(draft.transactionId)' in mobile_link
    assert 'method: "POST"' in mobile_link
    assert 'api("/api/v1/transactions"' not in mobile_link


def test_mobile_link_discards_detached_or_navigated_candidate_loads():
    javascript = source("app.js")
    mobile_link = javascript[
        javascript.index("async function openMobilePlanLink"):
        javascript.index("function transactionEditAccountChoices")
    ]

    assert "workspaceId: state.context.workspace.id" in mobile_link
    assert "view: state.activeView" in mobile_link
    assert "state.context?.workspace?.id === requestContext.workspaceId" in mobile_link
    assert "state.activeView === requestContext.view" in mobile_link
    assert "requestContext.opener?.isConnected" in mobile_link
    assert mobile_link.count("if (!requestIsCurrent()) return") == 2
    stale_guard = mobile_link.index("if (!requestIsCurrent()) return")
    state_write = mobile_link.index("state.planLinkTransactions = page.items")
    sheet_open = mobile_link.index("openMobileSheet({")
    assert stale_guard < state_write < sheet_open


def test_mobile_sheet_can_disable_primary_until_link_choices_are_complete():
    javascript = source("app.js")
    overlay = javascript[
        javascript.index("function renderMobileOverlay"):
        javascript.index("function closeMobileOverlay")
    ]

    assert 'typeof entry.primaryDisabled === "function"' in overlay
    assert "Boolean(entry.primaryDisabled())" in overlay
    assert "primaryDisabled: config.primaryDisabled || false" in overlay


def test_plan_ui_has_no_ledger_or_period_mutation_path():
    javascript = plan_source()

    for forbidden in (
        "/operations/spend", "/operations/add-funds", "/operations/transfer",
        "/account-periods/", "/reconcile", "operationsUndoCandidate",
    ):
        assert forbidden not in javascript


def test_desktop_plan_history_and_dialogs_remain_available():
    html = source("index.html")
    javascript = plan_source()

    for dialog_id in ("plan-rule-dialog", "plan-rule-detail-dialog", "plan-link-dialog"):
        assert f'id="{dialog_id}"' in html
    assert 'if (isMobileViewport()) {' in javascript
    assert '$("plan-rule-dialog").showModal()' in javascript
    assert '$("plan-rule-detail-dialog").showModal()' in javascript
    assert '$("plan-link-dialog").showModal()' in javascript
    assert "function renderPlanRuleDetail" in javascript
    assert 'planOccurrenceNode(item)' in javascript


def test_mobile_plan_and_analytics_geometry_is_bounded():
    css = source("style.css")

    assert ".plan-summary.mobile-metric-strip { height: 64px; min-height: 64px; max-height: 64px; }" in css
    assert ".mobile-plan-occurrence { display: grid; width: 100%; height: 64px; min-height: 64px; max-height: 64px;" in css
    assert ".mobile-plan-item-actions { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));" in css
    assert "#view-analytics .analytics-placeholder > span { width: 52px; height: 52px;" in css
